server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nest
    static_configs:
      - targets:
          - localhost
        labels:
          job: nest
          __path__: /var/log/myapp/*/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            pid: pid
            hostname: hostname
            method: method
            service: service
            params: params
      - labels:
          level:
          service:
          method:
      - timestamp:
          source: time
          format: unix_ms
      - output:
          source: msg
